version: '3.5'
services:
  mysql:
    image: mysql:5.7
#    container_name: php-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    network_mode: bridge  
  app:
    image: pedrotti/php-cli
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    container_name: php-app
    working_dir: /var/www/html
    links:
       - mysql:dbhost
    volumes:
      - .:/var/www/html
    ports:
        - 8000:8000
    command: php -S 0.0.0.0:8000 app.php
    network_mode: bridge